### ISSUE TITLE
Using this library breaks TimeSpan properties when seeding data

### ISSUE THREAD

**Issue by aholland1973** [ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly#12]
Using this library prevents TimeSpan properties being used with localdb (at least) as any attempt to seed TimeSpan properties in entities results in the exception "Input string was not in a correct format." occurring during EF migration:

System.FormatException: Input string was not in a correct format.
   at System.Globalization.TimeSpanFormat.FormatCustomized(TimeSpan value, ReadOnlySpan`1 format, DateTimeFormatInfo dtfi, ValueStringBuilder& result)
   at System.Globalization.TimeSpanFormat.TryFormat(TimeSpan value, Span`1 destination, Int32& charsWritten, ReadOnlySpan`1 format, IFormatProvider formatProvider)
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(IFormatProvider provider, String format, Object arg0)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.SqlServerTimeOnlyTypeMapping.GenerateNonNullSqlLiteral(Object value) in /_/EFCore.SqlServer.DateOnlyTimeOnly/Storage/SqlServerTimeOnlyTypeMapping.cs:line 79
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.GenerateProviderValueSqlLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Update.UpdateSqlGenerator.AppendSqlLiteral(StringBuilder commandStringBuilder, IColumnModification modification, String tableName, String schema)
   at Microsoft.EntityFrameworkCore.Update.UpdateSqlGenerator.<>c.<AppendValues>b__24_0(StringBuilder sb, IColumnModification o, ValueTuple`3 p)
   at System.Text.StringBuilderExtensions.AppendJoin[T,TParam](StringBuilder stringBuilder, IEnumerable`1 values, TParam param, Action`3 joinAction, String separator)
   at Microsoft.EntityFrameworkCore.Update.UpdateSqlGenerator.AppendValues(StringBuilder commandStringBuilder, String name, String schema, IReadOnlyList`1 operations)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerUpdateSqlGenerator.AppendInsertMultipleRows(StringBuilder commandStringBuilder, IReadOnlyList`1 modificationCommands, List`1 writeOperations, Boolean& requiresTransaction)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerUpdateSqlGenerator.AppendBulkInsertOperation(StringBuilder commandStringBuilder, IReadOnlyList`1 modificationCommands, Int32 commandPosition, Boolean& requiresTransaction)
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.ApplyPendingBulkInsertCommands()
   at Microsoft.EntityFrameworkCore.SqlServer.Update.Internal.SqlServerModificationCommandBatch.Complete(Boolean moreBatchesExpected)
   at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateCommandBatches(IEnumerable`1 commandSet, Boolean moreCommandSets, Boolean assertColumnModification, ParameterNameGenerator parameterNameGenerator)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(InsertDataOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.<>c.<.cctor>b__82_28(MigrationsSqlGenerator g, MigrationOperation o, IModel m, MigrationCommandListBuilder b)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.SqlServerMigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass16_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Input string was not in a correct format.

The problem is easy to recreate, just enable this library and ensure that at least one entity has a TimeSpan property which you then include in seed data. Upon pushing EF migration, this exception will occur.

**Comment by aholland1973** [comment]
[ADOMovieDatabaseConsoleApp.zip](https://github.com/ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly/files/11424031/ADOMovieDatabaseConsoleApp.zip)

This is an example that demonstrates the problem described above. 

Applying the existing initial-create migration will cause the problem to occur.

**Comment by ErikEJ** [comment]
Interesting that the TimeOnly mapping is involved here at all.

**Comment by ErikEJ** [comment]
@roji FYI - any thoughts / suggestions.

I think this happens due to the check here: https://github.com/ErikEJ/EFCore.SqlServer.DateOnlyTimeOnly/blob/cd75938a1e33bd9d64451289ae0782b42fe0ca33/EFCore.SqlServer.DateOnlyTimeOnly/Storage/SqlServerTimeOnlyTypeMappingSourcePlugin.cs#L16

Wonder if I should change to something like:

```csharp
public virtual RelationalTypeMapping FindMapping(in RelationalTypeMappingInfo mappingInfo)
        {
            var clrType = mappingInfo.ClrType ?? typeof(HierarchyId);

            return typeof(HierarchyId).IsAssignableFrom(clrType)
                ? new SqlServerHierarchyIdTypeMapping(SqlServerTypeName, clrType)
                : null;
        }
```

**Comment by ErikEJ** [comment]
Seems that plugin mappings are given higher priority somehow - chening will most likely break scaffolding

**Comment by ErikEJ** [comment]
Maybe a bug in 

     protected override string GenerateNonNullSqlLiteral(object value)

**Comment by ErikEJ** [comment]
@roji Looks like this will cause a Invalid Cast exception in the EF Core 8 implementation in a case like this:

TimeOnly mapping

```csharp
protected override string GenerateNonNullSqlLiteral(object value)
        => ((TimeOnly)value).Ticks % 10000000 == 0 // Handle trailing decimal separator when no fractional seconds
            ? string.Format(CultureInfo.InvariantCulture, _timeFormats[0], value)
            : string.Format(CultureInfo.InvariantCulture, SqlLiteralFormatString, value);
```

Compared to the TimeSpan mapping

```csharp
protected override string GenerateNonNullSqlLiteral(object value)
        => value is TimeSpan { Milliseconds: 0 } // Handle trailing decimal separator when no fractional seconds
            ? string.Format(CultureInfo.InvariantCulture, _timeFormats[0], value)
            : string.Format(CultureInfo.InvariantCulture, SqlLiteralFormatString, value);
```

**Comment by ErikEJ** [comment]
@aholland1973 I have published https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly/7.0.4-preview1 which contains a fix for this issue, if you can test and confirm it works for you, then I will release 7.0.4

**Comment by aholland1973** [comment]
> @aholland1973 I have published https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly/7.0.4-preview1 which contains a fix for this issue, if you can test and confirm it works for you, then I will release 7.0.4

@ErikEJ Thanks, I and my students who found the issue initially (I'm a software engineering lecturer at a UK university) will give it a try and report back shortly! Thanks for dealing with this so quickly!

**Comment by roji** [comment]
@ErikEJ do you know if this is something that needs to be fixed on the EF side as well?

**Comment by ErikEJ** [comment]
@roji Let me test the repo solution with EF Core 8, I am unsure but doubtful

**Comment by aholland1973** [comment]
> @aholland1973 I have published https://www.nuget.org/packages/ErikEJ.EntityFrameworkCore.SqlServer.DateOnlyTimeOnly/7.0.4-preview1 which contains a fix for this issue, if you can test and confirm it works for you, then I will release 7.0.4

I can confirm that against the example I posted, using this release does indeed resolve that specific problem.
